Repository pascal-zarrad/tc-discord-webhooks, pull requests merged in 2022-01, with the labels that each got.

#27 feat: add link to the build in notifications
  tc-discord-webhooks-server/src/main/java/com/github/playerforcehd/tcdiscordwebhooks/notificator/DiscordNotificator.java
Labels: C1 - enhancement

#28 Fix dev environment stop command
  README.MD
Labels: C3- documentation

#31 Move logo image to repository
  .github/tcdiscordwebhooks-logo-1024.png
  build/pom.xml
  pom.xml
  tc-discord-webhooks-server/pom.xml
  teamcity-plugin.xml
Labels: C6 -release
